apiVersion: v1
kind: Namespace
metadata:
  name: engineering-lab7
  labels:
    app.kubernetes.io/part-of: engineering
    lab: "7"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: runtime-quota
  namespace: engineering-lab7
spec:
  hard:
    requests.cpu: 1200m
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi
    pods: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: engineering-lab7
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: engineering-lab8
  labels:
    app.kubernetes.io/part-of: engineering
    lab: "8"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: runtime-quota
  namespace: engineering-lab8
spec:
  hard:
    requests.cpu: 1200m
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi
    pods: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: engineering-lab8
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: engineering-lab9
  labels:
    app.kubernetes.io/part-of: engineering
    lab: "9"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: runtime-quota
  namespace: engineering-lab9
spec:
  hard:
    requests.cpu: 1200m
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi
    pods: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: engineering-lab9
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
