apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineering-lab8-users
  namespace: engineering-lab8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engineering-lab8-users
  template:
    metadata:
      labels:
        app: engineering-lab8-users
    spec:
      containers:
        - name: users
          image: engineering-lab8-users:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4001
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 200m
              memory: 192Mi
---
apiVersion: v1
kind: Service
metadata:
  name: engineering-lab8-users
  namespace: engineering-lab8
spec:
  selector:
    app: engineering-lab8-users
  ports:
    - name: http
      port: 4001
      targetPort: 4001
  type: ClusterIP
