defaultRules:
  create: false

grafana:
  adminPassword: lab7-admin
  defaultDashboardsEnabled: true
  grafana.ini:
    server:
      domain: engineering.lab7.zelenkov-labs.ru
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
  livenessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 5
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
    failureThreshold: 18
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - engineering.lab7.zelenkov-labs.ru
    path: /grafana
    pathType: Prefix

prometheus:
  prometheusSpec:
    retention: 2h
    scrapeInterval: 15s
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

alertmanager:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
