apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: engineering-lab7-app
  namespace: engineering-lab7
  labels:
    app.kubernetes.io/name: engineering-lab7-app
    app.kubernetes.io/part-of: engineering-lab7
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engineering-lab7-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
